# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: story.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstory.proto\"+\n\x0c\x41udioRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\"M\n\rAudioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\r\n\x05\x61udio\x18\x04 \x01(\x0c\x32\x39\n\x0cStoryToAudio\x12)\n\x08Generate\x12\r.AudioRequest\x1a\x0e.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'story_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=15
  _globals['_AUDIOREQUEST']._serialized_end=58
  _globals['_AUDIORESPONSE']._serialized_start=60
  _globals['_AUDIORESPONSE']._serialized_end=137
  _globals['_STORYTOAUDIO']._serialized_start=139
  _globals['_STORYTOAUDIO']._serialized_end=196
# @@protoc_insertion_point(module_scope)
